name: Cache eed62be

on:
  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cache-step
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/eed62be-demo
          key: cache-eed62be

      - name: prime-cache-eed62be
        run: echo "cache-hit=${{ steps.cache.outputs.cache-hit }}"
